<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1FTEEH8" failures="13" tests="38" name="RestAssuredTest" time="26.58" errors="0" timestamp="2023-03-27T23:44:27 IST">
  <testcase classname="com.employeeapi.testcases.TC005_Delete_Employee_Record" name="@BeforeClass DeleteExistingEmployeeRecord" time="1.724">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testcases.TC005_Delete_Employee_Record.DeleteExistingEmployeeRecord(TC005_Delete_Employee_Record.java:35)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 17 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass DeleteExistingEmployeeRecord -->
  <testcase classname="com.employeeapi.testcases.TC005_Delete_Employee_Record" name="@AfterClass TearDown" time="-1.679940867574E9">
    <skipped/>
  </testcase> <!-- @AfterClass TearDown -->
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkContentType" time="0.018"/>
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkContentLength" time="0.028"/>
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkContentEncoding" time="0.021"/>
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkResponseTime" time="0.041">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcases.TC001_GET_All_Employees_Record.checkResponseTime(TC001_GET_All_Employees_Record.java:62)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseTime -->
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkStatusCode" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcases.TC001_GET_All_Employees_Record.checkStatusCode(TC001_GET_All_Employees_Record.java:47)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkStatusLine" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcases.TC001_GET_All_Employees_Record.checkStatusLine(TC001_GET_All_Employees_Record.java:73)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="getCookievalue" time="0.003"/>
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkServerType" time="0.128">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [nginx/1.21.6]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [nginx/1.21.6]
at com.employeeapi.testcases.TC001_GET_All_Employees_Record.checkServerType(TC001_GET_All_Employees_Record.java:95)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.employeeapi.testcases.TC001_GET_All_Employees_Record" name="checkResponseBody" time="0.259"/>
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkContentEncoding" time="0.008"/>
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkServerType" time="0.004"/>
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkStatusCode" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcases.TC002_GET_Single_Employee_Record.checkStatusCode(TC002_GET_Single_Employee_Record.java:43)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkStatusLine" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcases.TC002_GET_Single_Employee_Record.checkStatusLine(TC002_GET_Single_Employee_Record.java:69)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="getCookievalue" time="0.006"/>
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkContentLength" time="0.01"/>
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkResponseTime" time="0.026"/>
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkResponseBody" time="0.028"/>
  <testcase classname="com.employeeapi.testcases.TC002_GET_Single_Employee_Record" name="checkContentType" time="0.03">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testcases.TC002_GET_Single_Employee_Record.checkContentType(TC002_GET_Single_Employee_Record.java:80)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkResponseTime" time="0.008"/>
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkContentEncoding" time="0.01"/>
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkResponseBody" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcases.TC003_Post_Employee_Record.checkResponseBody(TC003_Post_Employee_Record.java:60)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkServerType" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [Apache]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [Apache]
at com.employeeapi.testcases.TC003_Post_Employee_Record.checkServerType(TC003_Post_Employee_Record.java:120)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkStatusCode" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcases.TC003_Post_Employee_Record.checkStatusCode(TC003_Post_Employee_Record.java:72)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkStatusLine" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcases.TC003_Post_Employee_Record.checkStatusLine(TC003_Post_Employee_Record.java:98)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="getCookievalue" time="0.004"/>
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkContentType" time="0.197"/>
  <testcase classname="com.employeeapi.testcases.TC003_Post_Employee_Record" name="checkContentLength" time="0.206"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkResponseTime" time="0.012"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkContentEncoding" time="0.022"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkContentLength" time="0.002"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkResponseBody" time="0.014"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkStatusCode" time="0.003"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkStatusLine" time="0.003"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="getCookievalue" time="0.004"/>
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkServerType" time="0.061">
    <failure type="java.lang.AssertionError" message="expected [nginx/1.14.1] but found [Apache]">
      <![CDATA[java.lang.AssertionError: expected [nginx/1.14.1] but found [Apache]
at com.employeeapi.testcases.TC004_Put_Employee_Record.checkServerType(TC004_Put_Employee_Record.java:122)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.employeeapi.testcases.TC004_Put_Employee_Record" name="checkContentType" time="0.062">
    <failure type="java.lang.AssertionError" message="expected [text/html; charset=UTF-8] but found [application/json]">
      <![CDATA[java.lang.AssertionError: expected [text/html; charset=UTF-8] but found [application/json]
at com.employeeapi.testcases.TC004_Put_Employee_Record.checkContentType(TC004_Put_Employee_Record.java:111)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapi.testcases.TC005_Delete_Employee_Record" name="checkStatusCode" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcases.TC005_Delete_Employee_Record" name="checkResponseBody" time="0.0">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
</testsuite> <!-- RestAssuredTest -->
